# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-17 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='district',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u0420\u0430\u0439\u043e\u043d'),
        ),
    ]
