# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-03 03:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='keywords',
            field=models.TextField(blank=True, help_text='\u041a\u043b\u044e\u0447\u0438\u0432\u044b\u0435 \u0441\u043b\u043e\u0432\u0430 \u0434\u043b\u044f \u043f\u043e\u0438\u0441\u043a\u0430 \u042f\u043d\u0434\u0435\u043a\u0441 \u0438 googla \u0441\u043b\u043e\u0432\u0430 \u0434\u043e\u0431\u0430\u0432\u043b\u0435\u0442 \u0447\u0435\u0440\u0435\u0437 \u0437\u0430\u043f\u044f\u0442\u0443\u044e', verbose_name='\u041a\u043b\u044e\u0447\u0438\u0432\u044b\u0435 \u0441\u043b\u043e\u0432\u0430'),
        ),
    ]
