# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-13 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_auto_20200413_0719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='from_the_sea',
            field=models.IntegerField(blank=True, default=0, help_text='\u0435\u0441\u043b\u0438 \u043d\u0435 \u043d\u0443\u0436\u043d\u043e \u043e\u0442\u043c\u0435\u0447\u0430\u0442\u044c \u0441\u043a\u043e\u043b\u044c\u043a\u043e \u043e\u0442 \u043c\u043e\u0440\u044f \u043e\u0441\u0442\u0430\u0432\u044c\u0442\u0435 <<\u043d\u043e\u043b\u044c>>', verbose_name='\u043e\u0442 \u043c\u043e\u0440\u044f'),
        ),
    ]
