# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-23 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='land_area',
            field=models.IntegerField(default=0, verbose_name='\u043f\u043b\u043e\u0449\u0430\u0434\u044c \u0443\u0447\u0430\u0441\u0442\u043a\u0430'),
        ),
        migrations.AddField(
            model_name='listing',
            name='terrace_area',
            field=models.IntegerField(default=0, verbose_name='\u043f\u043b\u043e\u0449\u0430\u0434\u044c \u0442\u0435\u0440\u0440\u0430\u0441\u044b'),
        ),
        migrations.AlterField(
            model_name='listing',
            name='lot_size',
            field=models.CharField(max_length=200, verbose_name='\u043d\u043e\u043c\u0435\u0440 ID'),
        ),
    ]
