# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-04 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200603_0323'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='floors',
            field=models.IntegerField(default=0, verbose_name='\u042d\u0442\u0430\u0436\u0438'),
        ),
    ]
