# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-29 11:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200423_0418'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.IntegerField(verbose_name='\u0446\u0435\u043d\u0430'),
        ),
    ]
