# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-13 08:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_auto_20200413_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='zipcode',
        ),
    ]
