# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-05-02 09:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_auto_20200429_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='price',
            field=models.CharField(max_length=200, verbose_name='\u0446\u0435\u043d\u0430'),
        ),
    ]
