# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-28 14:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_auto_20200628_1307'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='tip_name_en',
            field=models.CharField(blank=True, help_text='\u0422\u0438\u043f \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u044c', max_length=100, null=True, verbose_name='\u0422\u0438\u043f'),
        ),
        migrations.AddField(
            model_name='listing',
            name='tip_name_ru',
            field=models.CharField(blank=True, help_text='\u0422\u0438\u043f \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u044c', max_length=100, null=True, verbose_name='\u0422\u0438\u043f'),
        ),
        migrations.AddField(
            model_name='listing',
            name='vid_name_en',
            field=models.CharField(blank=True, help_text='\u0412\u0438\u0434 \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438 \u043d\u0430 \u043f\u0440\u0438\u043c\u0435\u0440 \u043d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0439', max_length=100, null=True, verbose_name='\u0432\u0438\u0434'),
        ),
        migrations.AddField(
            model_name='listing',
            name='vid_name_ru',
            field=models.CharField(blank=True, help_text='\u0412\u0438\u0434 \u043d\u0435\u0434\u0432\u0438\u0436\u0438\u043c\u043e\u0441\u0442\u0438 \u043d\u0430 \u043f\u0440\u0438\u043c\u0435\u0440 \u043d\u043e\u0432\u043e\u0441\u0442\u0440\u043e\u0439', max_length=100, null=True, verbose_name='\u0432\u0438\u0434'),
        ),
    ]
